name: Specs

jobs:
  specs:
    strategy:
      fail-fast: false
      matrix:
        task: [SPECS]
        ruby: ['2.7', '3.0']
        os: [ubuntu-20.04]

    name: ${{ matrix.task }} / ${{ matrix.os }} / Ruby ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set build image var
        run: echo "ImageVersion=$ImageVersion"  >> $GITHUB_ENV

      - name: Checkout git
        uses: actions/checkout@v1

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        if: ${{ matrix.ruby != 'system' }}
        with:
          ruby-version: ${{ matrix.ruby }}

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: gems@v1-${{ matrix.os }}-${{ env.ImageVersion }}-Ruby${{ matrix.ruby }}-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            gems@v1-${{ matrix.os }}-${{ env.ImageVersion }}-Ruby${{ matrix.ruby }}-

      - name: Run bundle install
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3 --without debugging documentation

      - name: Run Tests
        run: bundle exec rake spec
        env:
          COCOAPODS_CI_TASKS: ${{ matrix.task }}

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
